### ISSUE TITLE
Location autocompletions

### ISSUE THREAD

**Issue by chrdiller** [avahowell/masterkey#8]
Hey,

I am missing autocompletions for the locations stored in the vault so I started implementing this functionality. However, I saw you started working on that as well in the brach get-autocompletions. Your implementation also seems to be more intelligent than mine.
Is there a reason you haven't merged it yet? Would love to see it in master :)

Thanks
Christian

**Comment by avahowell** [comment]
Closing this since it's no longer relevant, and autocompletions have been added to the `-repl` interface.
