### ISSUE TITLE
Build failure due to termui changes

### ISSUE THREAD

**Issue by jbramsden** [avahowell/masterkey#9]
UI.go needs to be updated so that the new changes in github.com/gizak/termui are reflected in the code. E.G termui.Par type no longer exists instead of import github.com/gizak/termui/widgets and use widgets.Paragraph.

I did try to make some quick changes but it looks like a lot has changed to termui and lots need to change in the code:
# github.com/avahowell/masterkey
./ui.go:82:4: ls.ItemFgColor undefined (type *widgets.List has no field or method ItemFgColor)
./ui.go:83:4: ls.Height undefined (type *widgets.List has no field or method Height)
./ui.go:83:14: undefined: widgets.TermHeight
./ui.go:84:4: ls.BorderLabel undefined (type *widgets.List has no field or method BorderLabel)
./ui.go:85:39: ls.Height undefined (type *widgets.List has no field or method Height)
./ui.go:86:4: ls.Items undefined (type *widgets.List has no field or method Items)
./ui.go:89:30: too many arguments in call to widgets.NewParagraph
	have (string)
	want ()
./ui.go:90:6: spar.Height undefined (type *widgets.Paragraph has no field or method Height)
./ui.go:91:6: spar.Width undefined (type *widgets.Paragraph has no field or method Width)
./ui.go:453:59: undefined: termui.Bufferer
./ui.go:91:6: too many errors

**Comment by pepa65** [comment]
Same here, I was going to report this too.

**Comment by avahowell** [comment]
Thanks for the heads up. In the mean time, since this package supports the golang `dep` tool, you should be able to install it (https://github.com/golang/dep) and run `dep ensure` to get the build working. This should be the general practice for building masterkey.

**Comment by avahowell** [comment]
I checked in the vendor directory, so `go get` should work directly now.

**Comment by jbramsden** [comment]
Thanks for the quick response @avahowell!
Apologies I did not check the project to see if it was supporting `dep`. 
Once I did a `dep ensure` it worked!
